version: 0.0.1
# the only required property is resourcePackage, for more config options see below
swagger:
  resourcePackage: com.hawkeye.api.server.examples.hello.service

# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 8081
  adminConnectors:
    - type: http
      port: 8082
  requestLog:
    type: external

logging:
  type: external